[workspace]
authors = ["Wenzel Uhlmann <wenzel.uhlmann@gmx.de>"]
channels = ["conda-forge"]
name = "snow_causal_inference"
version = "0.1.0"
platforms = [
  "linux-64",
  { name = "gpu", platform = "linux-64", cuda = "12.6" },
]

[tasks]

[dependencies]
tigramite = ">=5.2.10.1,<6"
pandas = ">=3.0.5,<4"
pip = ">=26.2.1,<27"
notebook = ">=7.6.2,<8"
jupyter = ">=1.1.1,<2"
ipykernel = ">=7.3.0,<8"
matplotlib = ">=3.11.1,<4"
networkx = ">=3.6.1,<4"
scikit-learn = ">=1.9.0,<2"
numba = ">=0.67.0,<0.68"
dcor = ">=0.7,<0.8"

[feature.gpu]
platforms = ["gpu"]

[feature.gpu.dependencies]
cuda-version = "12.6.*"
pytorch-gpu = ">=2.5,<3"
gpytorch = ">=1.15.2,<2"

[feature.cpu]
platforms = ["linux-64"]

[feature.cpu.dependencies]
pytorch-cpu = ">=2.5,<3"

[environments]
default = ["cpu"]
gpu = ["gpu"]
